server:
  port: 21024
  servlet:
    context-path: /
    session:
      persistent: false

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /**
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  main:
    allow-bean-definition-overriding: false

standalone:
  data:
    path: F:\infiniq\data.viewer\data
  view:
    static: http://localhost:21024


