package com.infiniq.ams.standalone.domain.vo;

import lombok.Data;

import java.util.List;

@Data
public class TaskWorkTicketVo extends AbstractPagingRequestVo {
    private static final long serialVersionUID = 1L;
    private Long projectSeq;
    private Long taskSeq;
    private String workTicketId;
    private String status;
    private String statusReview;
    private String statusInspect;
    private String annotatorId;
    private String reviewerId;
    private String inspectorId;
    private String assignedDatetime;
    private String workedDatetime;
    private String reviewAssignedDatetime;
    private String reviewedDatetime;
    private String inspectAssignedDatetime;
    private String inspectedDatetime;
    private String workedDate;
    private String reviewedDate;
    private String inspectedDate;
    private boolean reOpen;
    private String registerId;
    private String registerDatetime;
    private String modifyId;
    private String modifyDatetime;
    private String projectId;
    private String taskId;
    private String userId;
    private String open;
    private String assign;
    private String worked;
    private String reviewAssign;
    private String reviewed;
    private String inspectionAssign;
    private String companyCode;
    private String reworkYn;
    private Integer assignedCnt;
    private Integer rvassignedCnt;
    private Integer inspAssignedCnt;
    private Integer openCnt;
    private Integer workedCnt;
    private Integer reviewedCnt;
    private int totalReview;
    private int pass;
    private int fail;
    private int ok;
    private int ng;
    private int reviewPoint;
    private int point;
    private String userName;
    private String taskType;
    private String prjWorkDivision;
    private String reviewMessage;
    private List<String> fileNameList;
    private List<String> inspectNgPrjInspErNums;
    private String reqType;
    private String[] workTicketIds;
    private String[] filterValidation;
    private String inspectionSysType;
    private String filterStatus;
    private Integer objectCount;
    private String[] classes;
    private String sort;
    private Long reviewAttachGroupSeq;
    private Long inspectAttachGroupSeq;
    private String reviewFailData;
    private Integer reviewFailCount;
    private String reviewFileName;
    private String inspectMessage;
    private boolean isProjectOwner;
    private String filterClass;
    private String filterTag;
    private String filterTagValue;
    private String filterObjectCount;
    private long perPage;
    private List<String> imgObjectIdList;
    private List<ObjectCheckVo> objectCheckList;
    private List<ClassCheckTaskVo> taskList;
    private List<String> workTicketIdList;
    private String remoteRegion;
    private String prjWorkType;
    private String rvassignedYn;
    private String tagId;
    private String objectTagId;
    private String rawFileId;
    private String objectGroupInfo;
    private String workPosition;
    private Integer countFail;
    private String operator;
    private String workFormType;
    private String masterId;
    private String masterComment;
}
